Testing/2.0.8
bincrafters/conan-sdl2 pull request #14
Opened 2018-11-01 02:13 UTC by Croydon

2018-11-01 03:02 UTC, uilianries approved these changes
LGTM

2018-11-01 10:25 UTC, Croydon commented
Urgh. @uilianries Any ideas where this is coming from? https://travis-ci.org/bincrafters/conan-sdl2/jobs/449155334#L1758

2018-11-01 11:07 UTC, uilianries commented
looks like is related to python2.7-minimal package. conanio Docker images are running /usr/bin/python as python 3.7. Maybe will be necessary install python2.7 full.

2018-11-01 11:09 UTC, Croydon commented
It only fails in the GCC 4.9 containers (with Python 3.6) 🤔

2018-11-01 11:14 UTC, uilianries commented
Both gcc-4.8 and gcc-4.9 use old Ubuntu distros, I used some workarounds to install python3.6. going to check now. thanks for reporting

2018-11-06 08:29 UTC, SSE4 requested changes
this one seems to be messed up, there are conflict markers within files, please fix it

2018-11-06 08:29 UTC, SSE4 commented on conanfile.py
> +<<<<<<< HEAD
conflict marker

2018-11-06 08:29 UTC, SSE4 commented on conanfile.py
> +=======
conflict marker

2018-11-06 08:29 UTC, SSE4 commented on conanfile.py
> +>>>>>>> stable/2.0.8
conflict marker

2018-11-06 08:29 UTC, SSE4 commented on conanfile.py
> +<<<<<<< HEAD
conflict marker

2018-11-06 08:29 UTC, SSE4 commented on conanfile.py
> +=======
conflict marker

2018-11-06 08:29 UTC, SSE4 commented on conanfile.py
> +<<<<<<< HEAD
conflict marker

2018-11-06 08:29 UTC, SSE4 commented on conanfile.py
> +>>>>>>> stable/2.0.8
conflict marker

2018-11-06 08:29 UTC, SSE4 commented
@Croydon there are conflict markers within conanfile, please fix it

2018-11-06 08:44 UTC, Croydon commented
@SSE4 Please read the pull request history. I didn't even push this

2018-11-06 09:28 UTC, SSE4 commented
@Croydon so what should we do? revert last commit?

2018-11-06 09:30 UTC, Croydon commented
@solvingj ^

2018-11-06 16:03 UTC, solvingj commented
Looks like was a mistake. Apologies, need to look more closely.

2018-11-07 09:35 UTC, merged